### ISSUE TITLE
Cue copy problem

### ISSUE THREAD

**Issue by actor125** [FrancescoCeruti/linux-show-player#41] opened 2016-10-25 01:10 UTC
When using ctrl+drag/drop to copy a cue a random cue gets copied instead of the selected cue.

**Comment by actor125** [comment] 2016-10-25 01:10
Working in list view in particular

**Comment by FrancescoCeruti** [comment] 2016-10-25 09:06
I cannot reproduce this exactly, what I can get is that the copied cue is always the _highlighted_ one, and not the one you drag, you can check this by looking at the drop-indicator showing the _highlighted_ cue name instead of the one you are trying to copy.

Can you confirm that this is your issues?

**Comment by actor125** [comment] 2016-10-25 18:14
It's not my issue is how I described it. I'm going to look at it again
tonight,  but I was getting  the impression  that it might be related  to
your existing qt5 issue. I also can't get shortcut keys to work. I also
can't move cues in the list. When  I do they retain their old cue number.
I'll get more details and shoot u another message asap.
Thanks so much for the response!
Ed

**Comment by FrancescoCeruti** [comment] 2016-10-25 21:19
That's weird, are you using the 0.4.1 version, right?
Can you tell me the distro and the desktop environment in use?

If you are using Ubuntu Unity the shortcut problem is "explained" in the issue #4

**Comment by actor125** [comment] 2016-10-27 15:48
Ubuntu 16.04. LiSP version 0.4fix1.  I did apt-get remove appmenu-qt5. It
had no effect that I can tell. LiSP still wont let me reorder, copy, and
gives me several graphical glitches when i try.

**Comment by FrancescoCeruti** [comment] 2016-10-28 04:34
I will give it a try asap, but as far as I can tell the 0.4.1 version is working correctly, so my advise is to update to the last version.

**Comment by FrancescoCeruti** [comment] 2016-10-28 12:34
Ok, so it's actually the same as reported in issue #20, that has been fixed in the 0.4.1 release.

**Closed** 2016-11-05 12:02 UTC
Labels: duplicate, UI
