### ISSUE TITLE
Keyboard shortcuts not working in Ubuntu (Unity)

### ISSUE THREAD

**Issue by tribut** [FrancescoCeruti/linux-show-player#4] opened 2015-10-10 16:27 UTC
Installed on Ubuntu 15.10 from source. Looks great so far, however when pressing the keyboard shortcuts (such as "CTRL-N" and "F11") nothing happens. Tried to launch with `-l debug` but there is no output when keys are pressed. How can I help debug this?

**Comment by FrancescoCeruti** [comment] 2015-10-10 16:59
Mmmh, probably it's related to qt5 and ubuntu, not the first time that some strange behaviour appen with ubuntu's qt5, and no useful output was given.
Give me some time so I can install Ubuntu 15.10 and test the application on it to find a solution.

**Comment by tribut** [comment] 2015-10-10 17:38
Of course, thanks again for a great piece of software.

**Comment by FrancescoCeruti** [comment] 2015-10-10 19:36
So, it's actually a "bug" in appmenu-qt5, caused by some change in the qt5 codebase, and hard to solve unless ubuntu-devs create a patch for qt5.
I've discovered 2/3 workarounds:
 * removing appmenu-qt5 and get the default menu (looks ugly);
 * the one before + changes unity with something that doesn't use appmenu-qt5;
 * a bad :confounded: code hack, that I'd really like to avoid

The first and the second, obviously, works for all qt5 apps.

**Comment by tribut** [comment] 2015-10-10 19:46
Just looked through the open bugs in appmenu-qt5. If it's this bug, there might by a fix coming "soon-ish": https://bugs.launchpad.net/appmenu-qt5/+bug/1380702

**Comment by FrancescoCeruti** [comment] 2015-10-10 19:58
Good, I hope they will fix it in short time.

**Comment by FrancescoCeruti** [comment] 2018-06-07 13:36
Looks like there's a patch/fix for this, plus, since Ubuntu is now officially on Gnome 3 this should be less relevant.

closing

**Closed by FrancescoCeruti** 2018-06-07 13:36 UTC
Labels: UI, wontfix
