### ISSUE TITLE
Search Slider (in List view?) suddenly stops that track

### ISSUE THREAD

**Issue by fnetX** [FrancescoCeruti/linux-show-player#90] opened 2017-11-28 21:18 UTC
Layout: List
Area: Track (Playing / Stopped)
Action: Using the search slider in that track card.
Expected: The track continues at the selected position.
What really happened: The track stopped playing (if it was) and gets stopped (so it is no longer visible at the right)

Caught a log file like that:
```
fralix@hp-debian9:~$ "/media/fralix/Daten/bin/apps/Linux_Show_Player-v0.5-x86_64.AppImage"
/bin/bash: ./lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: ./lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)

(python3:2922): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed

(python3:2922): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed
```

I am unsure whether this is a problem with the project itself or more a gstreamer issue - please tell me if I was wrong!

**Just some general feedback:**
 _And now I want to thank you for the project :-) 
I discovered it today because I was looking for something similar to QLab (which I discovered yesterday at the local theatre) for my Linux system. I am the event technician in school (as a student) and was using Mixxx for everything until now. A few weeks ago at a larger event with a lot of things to play in I noticed that it is not suited very well for that ... so I just wanted to try out something new and I am impressed.
Let's test it on stage in a few weeks when there are christmas songs to play in for singing ..._

**Comment by FrancescoCeruti** [comment] 2017-11-29 16:59
Hi, glad you discovered LiSP :)

Are you playing `mp3` files, if so the issue is the same as #76, it's a bug within the AppImage version of GStreamer (or some library), in this case you can a) covert the files to another format b) install lisp manually (see the [wiki](https://github.com/FrancescoCeruti/linux-show-player/wiki/Install)).

let me know

**Comment by fralix** [comment] 2017-11-29 17:07
Hmm ... I am not sure. It might be a GStreamer problem with the AppImage but the problems are different.
Yes I use a lot of MP3 files and with wav it seemed to work ... 
But when modifying the start position manually in the properties everything goes fine.
I'll try to compile it by myself. Should I use the git version or check out the released version?

I actually wanted to start a presentation tool for linux systems in Rust (especially for video) but it might be more useful to extend that existing project ... may be after Christmas ;-)

**Comment by FrancescoCeruti** [comment] 2017-11-29 18:13
> 'll try to compile it by myself. Should I use the git version or check out the released version?

use the released version

**Comment by fralix** [comment] 2017-11-29 19:12
Hey, using pip gave me a segfault but I tried your AppImage Recipe and it did fix the problem.
When it is a AppImage problem - is this problem for everyone using that AppImage or just for me because of my system? If it is the first thing you should consider correcting the AppImage.

**Comment by FrancescoCeruti** [comment] 2017-11-29 21:36
The AppImage have all the libraries bundled inside, so it's very likely that the problem affect all the users, I'm aware of it, but repackaging with a different version of GStreamer while keeping compatibility for older distributions its not going to be an easy thing.

Unfortunately I don't have too much time so I'm giving priority at developing the new version

**Comment by fralix** [comment] 2017-11-30 15:59
You might give a note at the download site and link to this issue so someone could fix that himself. 
Would a donation help you much or is it mainly the time that matters?

**Comment by FrancescoCeruti** [comment] 2017-11-30 16:06
It's a problem with time, I can upload an alternative version that it's not compatible with older distributions but that solves this problem

**Comment by fralix** [comment] 2017-11-30 16:15
Great ... so I will have a look at this project to see if I can in fixing easy stuff.

**Comment by FrancescoCeruti** [comment] 2017-12-03 01:02
I've replaced the AppImage download  with a `0.5-1` version, on my tests the problem doesn't appear anymore. Since I've reused Ubuntu 16.04 as the base system the compatibility is the same as before.

I'll wait a confirm on your side before closing :)

**Closed** 2022-05-28 13:42 UTC
Labels: AppImage
