### ISSUE TITLE
segmentation fault when exiting program

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#18] opened 2016-05-22 17:17 UTC
When LiSP is exited using the `File > Exit` menu or using the window's `X` button, the program crashes with a segfault. This does not impact normal operation, but I thought you'd like to know.

```
./linux-show-player -l debug
Configuration is up to date
DEBUG:: ACTION-CUES: Loaded "CollectionCue"
DEBUG:: ACTION-CUES: Loaded "CommandCue"
DEBUG:: ACTION-CUES: Loaded "MidiCue"
DEBUG:: ACTION-CUES: Loaded "SeekAction"
DEBUG:: ACTION-CUES: Loaded "StopAll"
DEBUG:: ACTION-CUES: Loaded "VolumeControl"
DEBUG:: MODULES: Loaded "ActionCues"
DEBUG:: MODULES: Loaded "LoadBackend"
DEBUG:: MODULES: Loaded "MediaInfo"
DEBUG:: MODULES: Loaded "Midi"
INFO:: REMOTE: Session started at ('127.0.1.1', 8070)
DEBUG:: MODULES: Loaded "Remote"
DEBUG:: MODULES: Loaded "ReplayGain"
DEBUG:: MODULES: Loaded "UriChanger"
DEBUG:: PLUGINS: Loaded "Controller"
DEBUG:: PLUGINS: Loaded "Synchronizer"
DEBUG:: PLUGINS: Loaded "Triggers"
DEBUG:: PLUGINS: Initialized "Synchronizer"
DEBUG:: PLUGINS: Initialized "Triggers"
DEBUG:: PLUGINS: Initialized "Controller"
DEBUG:: PLUGINS: Reset "Synchronizer"
DEBUG:: PLUGINS: Reset "Triggers"
DEBUG:: PLUGINS: Reset "Controller"
DEBUG:: MODULES: Terminated "UriChanger"
DEBUG:: MODULES: Terminated "Midi"
DEBUG:: MODULES: Terminated "Remote"
DEBUG:: MODULES: Terminated "ReplayGain"
INFO:: REMOTE: Session ended
DEBUG:: MODULES: Terminated "MediaInfo"
DEBUG:: MODULES: Terminated "ActionCues"
DEBUG:: MODULES: Terminated "LoadBackend"
Segmentation fault
```

**Comment by FrancescoCeruti** [comment] 2016-05-22 22:31
I've noticed that myself, I will investigate the causes, thanks

**Comment by macdroid53** [comment] 2016-08-16 22:24
Just for another data point.

This happens in Ubuntu 16.04

**Comment by FrancescoCeruti** [comment] 2016-08-24 14:48
I believe the problem is related to some un-garbaged PyQt object, in the current git (master) version seems resolved, can someone give it a try? Thanks :)

**Comment by radiomike** [comment] 2016-08-24 15:42
I'll double check later, but I haven't seen this with the git (master) version for quite a while. This is on an up to date arch install.

**Comment by radiomike** [comment] 2016-08-24 23:07
Just checked and no segfault on exit.

**Comment by FrancescoCeruti** [comment] 2016-08-25 08:46
Good, same as me.
Additionally I've done a simple test on Debian 8.5 and I've got no segfault but I'll wait to close this, maybe someone else can test with different conditions

**Comment by macdroid53** [comment] 2016-08-25 11:01
I'll get the latest form git this weekend and give it try. I've been using the package version installed on Ubuntu Studio 16.04.

**Comment by macdroid53** [comment] 2016-08-27 18:41
I get no seg fault on close with the latest. :)

**Comment by FrancescoCeruti** [comment] 2016-08-28 12:49
Great, thanks :)

I close this, even if currently there is not a "definitive" solution to this problem and in the future it may arise again :sob:

**Closed by FrancescoCeruti** 2016-08-28 12:49 UTC
Labels: priority low
