### ISSUE TITLE
Large number of underlying C/C++ object has been deleted errors slows LiSP

### ISSUE THREAD

**Issue by Rob7000** [FrancescoCeruti/linux-show-player#236] opened 2022-03-03 12:42 UTC
Lots of underlying C/C++ object has been deleted errors 
On slower hardware, this makes the user interface unresponsive.

**To Reproduce**
1. Add a Media cue (something longer than 10 seconds)
2. Start the media cue
3. Stop the media cue
4. Start the same media cue again
5. Observer the number of errors increase 

**Expected behavior**
No errors from starting and stopping a media cue

**Linux Show Player version:**
develop branch

**OS Version**
Ubuntu 21.04
Lubuntu

**Comment by s0600204** [comment] 2022-03-06 17:16
Not seeing this myself (but then I'm not using Ubuntu on any of my devices).

* Do you know the exact commit sha-hash of `develop` that you're using?
* ...and the version of `PyQt5` you have installed?
    - ([Repology](https://repology.org/project/python:pyqt5/versions) reports that it should be `5.15.4`, is that correct?)
* How has `LiSP` been "installed"? (Flatpak, from source, etc.)
* How *recent* is the installation? (e.g. last week, last month)
    - ...and how recently was `PyQt5` installed/updated? (Before or after the installation of `LiSP`?)
* Any custom plugins in use?
* Is this happening on more than one machine?
    - (It's unclear if you're using a version of `Lubuntu` which is based on `Ubuntu 21.04`, or if these are two different computers.)
* Are you starting media cues via the UI, via OSC, or does it not make a difference?

(Sorry for the multitude of questions: just trying to work this out.)

**Comment by FrancescoCeruti** [comment] 2022-05-28 13:05
This happens when QT (C++) objects are deleted but, for some reason, the python wrappers are not.
I cannot reproduce it, even on Ubuntu 21.04, but I remember I've observed the same problem at some point, likely a bug in some PyQt version.

I'll close this for now.

**Closed by FrancescoCeruti** 2022-05-28 13:05 UTC
Labels: need more info
