### ISSUE TITLE
Cues stopped by media "Stop time" do not fade out

### ISSUE THREAD

**Issue by leonerd** [FrancescoCeruti/linux-show-player#267] opened 2023-05-22 09:08 UTC
**Describe the bug**
If a media file is stopped early due to reaching its "Stop time" setting, the sound stops instantly, not obeying any fade-out time that is set.

**To Reproduce**
1. Add a media file that is fairly long.
2. Give it a 3second fade out time
3. Set the media stop time to 10 seconds.
4. Hit "Go" on the cue.

**Expected behavior**
The file should play for 10 seconds total, a fade out beginning at the 7 seconds mark that continues for the final 3 seconds until it stops. (Or maybe plays for 10 seconds at full volume then an additional 3 seconds, making 13 total. I don't mind which it does).

**Actual behaviour**
The sound plays at 10 seconds full volume then stops abruptly.

**Linux Show Player version:**
- 0.5.3-1

**OS Version**
 - Debian testing

**Comment by leonerd** [comment] 2023-05-22 09:11
As a workaround, I can add an AutoNext collection cue that has a pre-wait time, which triggers the previous cue's FadeOutStop action, so it's no huge problem. But it is unexpected...

**Comment by FrancescoCeruti** [comment] 2023-05-23 20:21
Thanks for the report, I'm closing this as duplicate of #101, feel free to look there for more answers :)

**Closed** 2023-05-23 20:21 UTC
