### ISSUE TITLE
Stop all sometimes needs two clicks to stop all active cues

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#27] opened 2016-08-16 22:11 UTC
I have observed the following behavior in ListLayout:

First click on the stop all button stops current cue. Second click stops others.

I have not been able to document the required steps to duplicate on demand.

**Comment by FrancescoCeruti** [comment] 2016-08-22 10:44
Technically the "current cue" is the one selected, so if you run the StopAll, the "current cue" it's the StopAll, so, what do you mean with "current cue"?

Anyway this seems very strange since the stopAll cue looks at all the cues, the only possible cause is that the cues that you say are not stopped, are started after the StopAll execution (or in the middle of the execution but after being checked), without other details I cannot reproduce the described behavior.

**Comment by macdroid53** [comment] 2016-08-22 11:56
It may well have been a special case. I used a lot of collection cues to get fades and timings the way I wanted them to work for the show.

I'll see if I can define a scenario that shows it happening. But, several times, during the creation of the show when I'd be testing the sequence of cues, there would be more than one cue running and the first click on the "stop all" button would stop the highlighted cue and others would continue until I hit it again.

**Comment by radiomike** [comment] 2016-08-23 22:54
I was looking at this a little while ago. 

The initial "stop all" stops all cues, but any cues with fade outs will do just that - in list view you should see the time change colour. 
The second "stop all" stops the fades as well.

I think this behaviour is sensible, but I do wonder if some kind of panic button by default might make sense?  Though assigning a "stop all" to a key and a double press does accomplish this easily without losing your place in the list. Another thing to consider would be an option to turn "stop all" into "instant stop all"?

**Comment by nodiscc** [comment] 2016-08-24 05:36
Double "stop all" as panic button (don't wait for fades to end) is the most sensible behaviour. I don't think another button should be added for this.

**Comment by FrancescoCeruti** [comment] 2016-08-24 10:04
As already said the "Stop All" behaviour is exactly the same as normally stopping/pausing a cue, only done for all the cues.
The "double" stop that interrupt the fades is actually caused by some sort of bug (magically became a feature :laughing:) in the GStreamer backend code, unfortunately the way the media fadeout (when the cue is stopped) is implemented can be difficult to manage.

At this point I believe the behavior described in the first message:

> First click on the stop all button stops current cue. Second click stops others.

it's related to cues with fade-out, so what appears to be a non stopped cue is actually a fading-out cue.

If this behavior is somehow desirable, until we have an `interrupt` function for the cues, this can be leaved as it is, let me know.

**Comment by macdroid53** [comment] 2016-08-24 11:19
In other packages I've used:

Stop = stop (terminate) the currently selected cue
Fade = fade and terminate the currently selected cue
Stop All = stop and terminate all executing cues
Fade All = fade and terminate all executing cues
Fading from one volume level, while a cue is executing, to another is accomplished by an action cue.

I think is is more intuitive to have stop all really terminate all and if other behaviors are desired use action cues to define the desired behavior.

**Comment by FrancescoCeruti** [comment] 2016-08-24 11:31
Yeah, this can allow more flexibility, but if you are creating a simple show, having fade-out and fade-in integrated within the cue is very handy. You can decide to not use this feature and fade the cue only using other cues (currently `Volume Control` with a trigger to stop), doing so your `Media Cue(s)` do not fade when stopped manually or using, for example, a `Stop All` cue, a fade cue (`Volume Control`) can be stopped as any other cue to interrupted the fade.

**Comment by FrancescoCeruti** [comment] 2016-08-24 12:21
I've consider some options, and given your consideration I came to a conclusion: add an independent `FadeOut` to the possible actions of a cue, this will allow to choose to `Stop` (no fade) or `FadeOut` (fadeout and stop), in the cue setting will be possible to choose which one should be used as the default action when "clicking" the cue.

In addition this will make trivial eventually fade/fade-all "buttons" in the UI.

**Comment by macdroid53** [comment] 2016-08-24 12:51
Agreed, very nice.

**Comment by FrancescoCeruti** [comment] 2016-08-26 11:41
I close this in favor of the issues #25

**Closed by FrancescoCeruti** 2016-08-26 11:41 UTC
Labels: enhancement
